spring.datasource.url=jdbc:h2:file:./chatapp
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect


#spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=create

spring.thymeleaf.enabled=true
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

spring.mvc.view.prefix=
spring.mvc.view.suffix=


logging.level.root=INFO
logging.level.com.chatapp.chat_app=INFO


management.endpoints.web.exposure.include=health


#logging.file.name=archive/app.log
#logging.level.org.springframework.web=DEBUG

chat.nginx-url=http://localhost:8090

# this sets the total capacity to release the latch on init
chat.total-capacity=600
