spring.application.name=server



# this is default, will be overridden by docker
chat.main-app.url=http://localhost:8080

server.port=8081
chat.server.name=chat-server-1
chat.server.host=http://localhost:8081
chat.max-sessions=200


