upstream chat_servers {
    least_conn;

    server chat-server-1:8081;
    server chat-server-2:8081;
    server chat-server-3:8081;
}

server {
    listen 8090;



    # Health check — short timeout
    location /server/health {
        proxy_pass         http://chat_servers;
        proxy_read_timeout 5s;
    }

    # session assignment, used once per session
    location /server/sessions/assign {
        proxy_pass            http://chat_servers;
        proxy_read_timeout    10s;
        proxy_connect_timeout 5s;
        proxy_set_header Host            $host;
        proxy_set_header X-Real-IP       $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}