spring.datasource.url=jdbc:h2:file:./chatapp
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create

spring.thymeleaf.enabled=true
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

spring.mvc.view.prefix=
spring.mvc.view.suffix=

logging.level.root=INFO
logging.level.com.chatapp.chat_app=DEBUG
logging.file.name=logs/app.log
logging.level.org.springframework.web=DEBUG

# CHANGE THIS TO 1 FOR ITERATIVE SERVING and 82 for Forking ( since there is 82 entries )
chat.max-servers=82