spring.datasource.url=jdbc:sqlite:chatapp.db?date_class=TEXT
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=create

spring.thymeleaf.enabled=true
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

spring.mvc.view.prefix=
spring.mvc.view.suffix=

logging.level.root=INFO
logging.level.com.chatapp.chat_app=DEBUG
logging.file.name=logs/app.log
logging.level.org.springframework.web=DEBUG